//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Achievements()
        {
            this.PlayerAchievements = new HashSet<PlayerAchievements>();
        }
    
        public long AchievementID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long AchievementCategoryID { get; set; }
        public string ActionToEarn { get; set; }
        public int Points { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual AchievementCategories AchievementCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAchievements> PlayerAchievements { get; set; }
    }
}
