//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertEvents
    {
        public long AlertEventID { get; set; }
        public System.DateTime AlertDateTime { get; set; }
        public string AlertType { get; set; }
        public string AlertDescription { get; set; }
        public Nullable<long> PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerEmail { get; set; }
        public Nullable<bool> PlayerActive { get; set; }
        public Nullable<long> TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<long> LeagueID { get; set; }
        public string LeagueName { get; set; }
        public Nullable<long> WebhookID { get; set; }
        public bool Dismissed_ByAdmin { get; set; }
        public Nullable<System.DateTime> DismissedDateTime_ByAdmin { get; set; }
        public Nullable<long> DismissedByAdminUserID { get; set; }
        public bool Dismissed_ByCoach { get; set; }
        public Nullable<System.DateTime> DismissedDateTime_ByCoach { get; set; }
        public Nullable<long> DismissedByCoachUserID { get; set; }
        public bool AutoDismiss { get; set; }
        public Nullable<System.DateTime> AutoDismissDateTime { get; set; }
        public Nullable<long> AutoDismissBy_UserID { get; set; }
        public byte[] RowVersion { get; set; }
        public string AdminUserFullName { get; set; }
        public string CoachUserFullName { get; set; }
        public string AutoDismissByUserFullName { get; set; }
        public Nullable<bool> IsFundedPlayer { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual AlertEvents AlertEvents1 { get; set; }
        public virtual AlertEvents AlertEvents2 { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
