//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberToolsBenefits
    {
        public long MemberToolsBenefitID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string PictureName { get; set; }
        public string Link { get; set; }
        public int SortOrder { get; set; }
        public bool IsTool { get; set; }
        public bool IsBenefit { get; set; }
    }
}
