//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMeasurements
    {
        public long PlayerMeasurementID { get; set; }
        public long PlayerID { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<decimal> Neck { get; set; }
        public Nullable<decimal> RightBicep { get; set; }
        public Nullable<decimal> LeftBicep { get; set; }
        public Nullable<decimal> Waist { get; set; }
        public Nullable<decimal> Hips { get; set; }
        public Nullable<decimal> RightThigh { get; set; }
        public Nullable<decimal> LeftThigh { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
