//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDashboard
    {
        public long PlayerDashboardID { get; set; }
        public long PlayerID { get; set; }
        public string DashboardURL { get; set; }
        public string DashboardPassword { get; set; }
        public Nullable<decimal> TargetWeight { get; set; }
        public string PasswordResetCode { get; set; }
        public Nullable<System.DateTime> ResetCodeExpiry { get; set; }
        public bool Locked { get; set; }
        public bool Deleted { get; set; }
        public bool IsFirstLogin { get; set; }
        public bool Share_FoodnDrink { get; set; }
        public Nullable<int> Share_FoodnDrinkDataFrequency { get; set; }
        public Nullable<int> Share_FoodnDrinkDataWith { get; set; }
        public int Share_FoodnDrinkDayOfWeek { get; set; }
        public string Share_FoodnDrinkAdditionalRecipients { get; set; }
        public bool Share_WeeklyActivity { get; set; }
        public Nullable<int> Share_WeeklyActivityDataFrequency { get; set; }
        public Nullable<int> Share_WeeklyActivityDataWith { get; set; }
        public int Share_WeeklyActivityDayOfWeek { get; set; }
        public string Share_WeeklyActivityAdditionalRecipients { get; set; }
        public bool Share_Achievements { get; set; }
        public Nullable<int> Share_AchievementsDataFrequency { get; set; }
        public Nullable<int> Share_AchievementsDataWith { get; set; }
        public int Share_AchievementsDayOfWeek { get; set; }
        public string Share_AchievementsAdditionalRecipients { get; set; }
        public bool Share_Weight_Measurements { get; set; }
        public Nullable<int> Share_Weight_MeasurementsDataFrequency { get; set; }
        public Nullable<int> Share_Weight_MeasurementsDataWith { get; set; }
        public int Share_Weight_MeasurementsDayOfWeek { get; set; }
        public string Share_Weight_MeasurementsAdditionalRecipients { get; set; }
        public string OptionalMessage { get; set; }
        public bool Enable2FactorAuth { get; set; }
        public bool EnableGoals { get; set; }
        public bool Reminder_Tracking { get; set; }
        public Nullable<int> Reminder_TrackingFrequency { get; set; }
        public int Reminder_TrackingDayOfWeek { get; set; }
        public bool Reminder_PlanActivity { get; set; }
        public Nullable<int> Reminder_PlanActivityFrequency { get; set; }
        public int Reminder_PlanActivityDayOfWeek { get; set; }
        public bool Reminder_WeighIn { get; set; }
        public Nullable<int> Reminder_WeighInFrequency { get; set; }
        public int Reminder_WeighInDayOfWeek { get; set; }
        public bool Reminder_ProgressPhotos { get; set; }
        public Nullable<int> Reminder_ProgressPhotosFrequency { get; set; }
        public int Reminder_ProgressPhotosDayOfWeek { get; set; }
        public bool Reminder_Measurements { get; set; }
        public Nullable<int> Reminder_MeasurementsFrequency { get; set; }
        public int Reminder_MeasurementsDayOfWeek { get; set; }
        public bool IsTrial { get; set; }
        public Nullable<System.DateTime> TrialExpiryDate { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
