//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerScoreBreakdowns
    {
        public long PlayerScoreBreakdownID { get; set; }
        public long PlayerID { get; set; }
        public decimal Percent5_Bonuses { get; set; }
        public decimal Percent10_Bonuses { get; set; }
        public decimal Hatricks { get; set; }
        public decimal OwnGoals { get; set; }
        public decimal TeamBonuses { get; set; }
        public decimal WeightGoals { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
