//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemMessages()
        {
            this.UserSystemMessages = new HashSet<UserSystemMessages>();
        }
    
        public long SystemMessageID { get; set; }
        public string SystemMessageSubject { get; set; }
        public string SystemMessage { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public long CreatedByUserID { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSystemMessages> UserSystemMessages { get; set; }
    }
}
