//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSettings
    {
        public long SystemSettingID { get; set; }
        public bool EmailsEnabled { get; set; }
        public bool SendTempEmail { get; set; }
        public string SupportEmailAddress { get; set; }
        public string TempEmailAddress { get; set; }
        public string CurrentDomain { get; set; }
        public string AdminEmailAddress { get; set; }
        public string GoCardless_Mode { get; set; }
        public string GoCardless_APIUrlLive { get; set; }
        public string GoCardless_TokenUrlLive { get; set; }
        public string GoCardless_ClientIDLive { get; set; }
        public string GoCardless_ClientSecretLive { get; set; }
        public string GoCardless_TokenLive { get; set; }
        public string GoCardless_APIUrlSandbox { get; set; }
        public string GoCardless_TokenUrlSandbox { get; set; }
        public string GoCardless_ClientIDSandbox { get; set; }
        public string GoCardless_ClientSecretSandbox { get; set; }
        public string GoCardless_TokenSandbox { get; set; }
        public decimal RegFeeWithBook { get; set; }
        public decimal RegFeeWithoutBook { get; set; }
        public string PayPal_Mode { get; set; }
        public string PayPalServerURL_Live { get; set; }
        public string BusinessEmail_Live { get; set; }
        public string NotifyURL_IPN_Live { get; set; }
        public string ReturnURL_Live { get; set; }
        public string PayPalServerURL_SandBox { get; set; }
        public string BusinessEmail_SandBox { get; set; }
        public string NotifyURL_IPN_SandBox { get; set; }
        public string ReturnURL_SandBox { get; set; }
        public decimal ResetLeagueWeightLoss { get; set; }
        public string GoCardless_WebhookIDSandbox { get; set; }
        public string GoCardless_WebhookIDLive { get; set; }
        public bool DownForMaintenance { get; set; }
        public string DownForMaintenance_Timer { get; set; }
        public string ReferralCandy_AccessID { get; set; }
        public string ReferralCandy_SecreteKey { get; set; }
        public decimal PremiumDashboardFee { get; set; }
        public string SystemMessage { get; set; }
        public string SystemMessageSubject { get; set; }
        public bool Enable_MobileVerification { get; set; }
    }
}
