//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public long AuditLogID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string AuditLogShortDesc { get; set; }
        public string AuditLogLongDesc { get; set; }
        public Nullable<long> UserID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
