//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDashboardNotifications
    {
        public long PlayerDashboardNotificationID { get; set; }
        public long PlayerID { get; set; }
        public long DashboardNotificationID { get; set; }
        public bool Dismissed { get; set; }
        public Nullable<System.DateTime> DismissedDateTime { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual DashboardNotifications DashboardNotifications { get; set; }
        public virtual Players Players { get; set; }
    }
}
