//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerWeightWeeks
    {
        public long PlayerWeightWeekID { get; set; }
        public long PlayerID { get; set; }
        public Nullable<decimal> Wk1 { get; set; }
        public Nullable<decimal> LossWk1 { get; set; }
        public Nullable<decimal> Wk2 { get; set; }
        public Nullable<decimal> LossWk2 { get; set; }
        public Nullable<decimal> Wk3 { get; set; }
        public Nullable<decimal> LossWk3 { get; set; }
        public Nullable<decimal> Wk4 { get; set; }
        public Nullable<decimal> LossWk4 { get; set; }
        public Nullable<decimal> Wk5 { get; set; }
        public Nullable<decimal> LossWk5 { get; set; }
        public Nullable<decimal> Wk6 { get; set; }
        public Nullable<decimal> LossWk6 { get; set; }
        public Nullable<decimal> Wk7 { get; set; }
        public Nullable<decimal> LossWk7 { get; set; }
        public Nullable<decimal> Wk8 { get; set; }
        public Nullable<decimal> LossWk8 { get; set; }
        public Nullable<decimal> Wk9 { get; set; }
        public Nullable<decimal> LossWk9 { get; set; }
        public Nullable<decimal> Wk10 { get; set; }
        public Nullable<decimal> LossWk10 { get; set; }
        public Nullable<decimal> Wk11 { get; set; }
        public Nullable<decimal> LossWk11 { get; set; }
        public Nullable<decimal> Wk12 { get; set; }
        public Nullable<decimal> LossWk12 { get; set; }
        public Nullable<decimal> Wk13 { get; set; }
        public Nullable<decimal> LossWk13 { get; set; }
        public Nullable<decimal> Wk14 { get; set; }
        public Nullable<decimal> LossWk14 { get; set; }
        public Nullable<decimal> LossPercent { get; set; }
        public Nullable<decimal> Five_BWV { get; set; }
        public Nullable<decimal> Ten_BWV { get; set; }
        public Nullable<decimal> TotalLost { get; set; }
        public Nullable<decimal> CurrentBMI { get; set; }
        public Nullable<decimal> StartWaist { get; set; }
        public Nullable<decimal> EndWaist { get; set; }
        public bool BMIUnder25 { get; set; }
        public bool RegWeightWarningDismissed { get; set; }
        public Nullable<bool> IsLossGain_5Occurred { get; set; }
        public bool IsLossGain_5Dismissed { get; set; }
        public Nullable<int> MissingWeekNum { get; set; }
        public Nullable<System.DateTime> Next2DaysMissingEmailDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
