//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerImages
    {
        public long PlayerImageID { get; set; }
        public long PlayerID { get; set; }
        public string FileName { get; set; }
        public bool IsFront { get; set; }
        public bool IsSide { get; set; }
        public bool IsAnimated { get; set; }
        public bool Display { get; set; }
        public bool DefaultImage { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public bool MarkForDeletion { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
