//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.AlertEvents = new HashSet<AlertEvents>();
            this.AlertEvents1 = new HashSet<AlertEvents>();
            this.AuditLogs = new HashSet<AuditLogs>();
            this.SystemMessages = new HashSet<SystemMessages>();
            this.UserSystemMessages = new HashSet<UserSystemMessages>();
        }
    
        public long UserID { get; set; }
        public long RoleID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public bool Locked { get; set; }
        public bool Deleted { get; set; }
        public string PasswordResetCode { get; set; }
        public Nullable<System.DateTime> ResetCodeExpiry { get; set; }
        public bool DailyStatEmails { get; set; }
        public bool DailyLiveLeagueNumEmails { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> MobileVerficationCode { get; set; }
        public bool IsMobileNumVerified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertEvents> AlertEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertEvents> AlertEvents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLogs> AuditLogs { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMessages> SystemMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSystemMessages> UserSystemMessages { get; set; }
    }
}
