//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANvFAT_Football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weights
    {
        public long WeightID { get; set; }
        public decimal kg { get; set; }
        public int lbs { get; set; }
        public int stones { get; set; }
        public int pounds { get; set; }
    }
}
